### ISSUE TITLE
TypeError: __init__(): incompatible constructor arguments for TopologicalReferenceKeypointOptimizer

### ISSUE THREAD

**Issue by karthik101200** [conda-forge/pixsfm-feedstock#22]
### Comment:

TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pixsfm._pixsfm._keypoint_adjustment.TopologicalReferenceKeypointOptimizer(arg0: pixsfm._pixsfm._keypoint_adjustment.TopologicalReferenceKeypointOptimizerOptions, arg1: pixsfm._pixsfm._keypoint_adjustment.KeypointAdjustmentSetup, arg2: pixsfm._pixsfm._base.InterpolationConfig)

Invoked with: {'loss': {'name': 'cauchy', 'params': [0.25]}, 'solver': {'function_tolerance': 0.0, 'gradient_tolerance': 0.0, 'parameter_tolerance': 1e-05, 'minimizer_progress_to_stdout': False, 'max_num_iterations': 100, 'max_linear_solver_iterations': 200, 'max_num_consecutive_invalid_steps': 10, 'max_consecutive_nonmonotonic_steps': 10, 'use_inner_iterations': False, 'use_nonmonotonic_steps': False, 'update_state_every_iteration': False, 'num_threads': 1}, 'print_summary': False, 'bound': 2.0, 'num_threads': -1}, <pixsfm._pixsfm._keypoint_adjustment.KeypointAdjustmentSetup object at 0x7fabc98f4e30>, {'nodes': [[0.0, 0.0]], 'mode': 'BICUBIC', 'l2_normalize': True, 'ncc_normalize': False, 'use_float_simd': False}

I am getting this issue

**Comment by Tobias-Fischer** [comment]
Please provide a minimum working example / failure case so we know how to reproduce the issue. Furthermore, please provide all requested information when opening an issue.

**Comment by karthik101200** [comment]
I apologize. I wanted to create a sparse pointcloud from known poses. I extract, match and triangulate features as provided in [Issue](https://github.com/cvg/pixel-perfect-sfm/issues/83#issue-1457850925). The command 
`python -m pixsfm.refine_hloc triangulator `
gives me this error 
As shown in [Issue](https://github.com/cvg/pixel-perfect-sfm/issues/106#issue-1765464404) I tried changing the code in site packages but didnt work. It also says the cause may be " libraries being linked to the wrong ceres library" [link](https://github.com/cvg/pixel-perfect-sfm/issues/106#issuecomment-1609138627).

**Comment by Tobias-Fischer** [comment]
Please create a new issue and provide all requested information. Many thanks!
