### ISSUE TITLE
Loosen colmap pin

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/pixsfm-feedstock#27]
The pin on colmap
https://github.com/conda-forge/pixsfm-feedstock/blob/c1e06da77cfd7a598ec7b1216fbff7493b1aae9e/recipe/meta.yaml#L68
prevents this feedstock from being migrated, for example for newer pytorch versions.

CC @conda-forge/pixsfm @hmaarrfk

**Comment by Tobias-Fischer** [comment]
See https://github.com/cvg/pixel-perfect-sfm/pull/138

**Comment by Tobias-Fischer** [comment]
I added colmap=3.8 and pycolmap=0.4.0 to the `abi_migration_branches` to we should be all good regarding migrations; closing here.
